# Generated by Django 3.0 on 2019-12-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='')),
                ('autor', models.CharField(default='desconhecido', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
